--- 
--- @class chip.utils.KeyCode
--- 
--- All keycodes taken from the [Love2D Wiki](https://love2d.org/wiki/KeyConstant)
---
local KeyCode = {
    NONE = "none",
    A = "a",
    B = "b",
    C = "c",
    D = "d",
    E = "e",
    F = "f",
    G = "g",
    H = "h",
    I = "i",
    J = "j",
    K = "k",
    L = "l",
    M = "m",
    N = "n",
    O = "o",
    P = "p",
    Q = "q",
    R = "r",
    S = "s",
    T = "t",
    U = "u",
    V = "v",
    W = "w",
    X = "x",
    Y = "y",
    Z = "z",
    SPACE = "space",

    ZERO = "0",
    ONE = "1",
    TWO = "2",
    THREE = "3",
    FOUR = "4",
    FIVE = "5",
    SIX = "6",
    SEVEN = "7",
    EIGHT = "8",
    NINE = "9",

    EXCLAMATION = "!",
    AT = "@",
    HASH = "#",
    DOLLAR = "$",
    PERCENT = "%",
    CARET = "^",
    AMPERSAND = "&",
    ASTERISK = "*",
    LPAREN = "(",
    RPAREN = ")",
    MINUS = "-",
    UNDERSCORE = "_",
    PLUS = "+",
    EQUALS = "=",
    GRAVE_ACCENT = "`",
    TILDE = "~",
    LBRACE = "{",
    RBRACE = "}",
    VBAR = "|",
    LBRACKET = "[",
    RBRACKET = "]",
    BACKSLASH = "\\",
    COLON = ":",
    SEMICOLON = ";",
    APOSTROPHE = "'",
    QUOTE = '"',
    LT = "<",
    GT = ">",
    QUESTION = "?",
    COMMA = ",",
    PERIOD = ".",
    SLASH = "/",

    NUMPAD_0 = "kp0",
    NUMPAD_1 = "kp1",
    NUMPAD_2 = "kp2",
    NUMPAD_3 = "kp3",
    NUMPAD_4 = "kp4",
    NUMPAD_5 = "kp5",
    NUMPAD_6 = "kp6",
    NUMPAD_7 = "kp7",
    NUMPAD_8 = "kp8",
    NUMPAD_9 = "kp9",
    NUMPAD_PERIOD = "kp.",
    NUMPAD_DIVIDE = "kp/",
    NUMPAD_MINUS = "kp-",
    NUMPAD_MULTIPLY = "kp*",
    NUMPAD_PLUS = "kp+",
    NUMPAD_ENTER = "kpenter",

    UP = "up",
    DOWN = "down",
    RIGHT = "right",
    LEFT = "left",
    HOME = "home",
    END = "end",
    PAGE_UP = "pageup",
    PAGE_DOWN = "pagedown",

    INSERT = "insert",
    BACKSPACE = "backspace",
    TAB = "tab",
    CLEAR = "clear",
    ENTER = "return",
    DELETE = "delete",

    F1 = "f1",
    F2 = "f2",
    F3 = "f3",
    F4 = "f4",
    F5 = "f5",
    F6 = "f6",
    F7 = "f7",
    F8 = "f8",
    F9 = "f9",
    F10 = "f10",
    F11 = "f11",
    F12 = "f12",
    F13 = "f13",
    F14 = "f14",
    F15 = "f15",
    F16 = "f16",
    F17 = "f17",
    F18 = "f18",

    NUM_LOCK = "numlock",
    CAPS_LOCK = "capslock",
    SCROLL_LOCK = "scrolllock",
    R_SHIFT = "rshift",
    L_SHIFT = "lshift",
    R_CTRL = "rctrl",
    L_CTRL = "lctrl",
    R_ALT = "ralt",
    L_ALT = "lalt",
    R_GUI = "rgui",
    L_GUI = "lgui",
    MODE = "mode",

    WWW = "www",
    MAIL = "mail",
    CALCULATOR = "calculator",
    COMPUTER = "computer",
    APP_SEARCH = "appsearch",
    APP_HOME = "apphome",
    APP_BACK = "appback",
    APP_FORWARD = "appforward",
    APP_REFRESH = "apprefresh",
    APP_BOOKMARKS = "appbookmarks",

    PAUSE = "pause",
    ESCAPE = "escape",
    HELP = "help",
    PRINT_SCREEN = "printscreen",
    SYS_REQ = "sysreq",
    MENU = "menu",
    APPLICATION = "application",
    POWER = "power",
    CURRENCY_UNIT = "currencyunit",
    UNDO = "undo",
}
return KeyCode